### ISSUE TITLE
Make new minor release

### ISSUE THREAD

**Issue by toothfairy** [coinsop/bittrex-wrapper#10]
@oliversd can you please make a minor release with latest changes?

**Comment by oliversd** [comment]
Hi @toothfairy  thank you for your contribution. 

The package is published [https://www.npmjs.com/package/bittrex-wrapper](https://www.npmjs.com/package/bittrex-wrapper) with version number 1.0.5.

If you have any problem let me know

**Comment by toothfairy** [comment]
Lovely! Thanks @oliversd
