### ISSUE TITLE
marketGetOpenOrders(market)  market must be an optional

### ISSUE THREAD

**Issue by russkiy78** [coinsop/bittrex-wrapper#7]
In according to Bittrex API in marketGetOpenOrders parameter "market" is optional.
Without "market" API should return all  opened orders.

Solution is in change 374 string of Bittrex.js :

`return Promise.reject(new Error('Market is required'));`

to:

`return this.doRequest(this.MARKET_GET_OPEN_ORDERS);`

**Comment by oliversd** [comment]
#8 closed thank you @russkiy78 for the pull request
